/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 Fruitstore.gltf 
Author: Tunnie (https://sketchfab.com/lktung611)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fruit-stall-highpoly-13eb04acf51145bd81bc280662ed87f5
Title: Fruit Stall (highpoly)
*/
import React from 'react';

import { useGLTF } from '@react-three/drei';

export function Fruitstore(props) {
  const { nodes, materials } = useGLTF('/models/fruit_stall/Fruitstore.gltf');
  return (
    <group {...props} dispose={null}>
      <group position={[0, -67.857, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <group position={[53.473, 11.139, 44.996]} scale={2.54}>
            <group position={[0, 0, -1.895]}>
              <mesh
                geometry={nodes.stick_watermelon_wood_0.geometry}
                material={materials.wood}
              />
              <mesh
                geometry={nodes['stick_watermelon_Material_#74_0'].geometry}
                material={materials.Material_74}
              />
              <mesh
                geometry={nodes['stick_watermelon_Material_#76_0'].geometry}
                material={materials.Material_76}
              />
              <mesh
                geometry={nodes['stick_watermelon_Material_#75_0'].geometry}
                material={materials.Material_75}
              />
            </group>
          </group>
          <group position={[-43.804, 11.304, 41.636]} scale={2.54}>
            <group position={[0, 0, -1.895]}>
              <mesh
                geometry={nodes.stick_pineapple_wood_0.geometry}
                material={materials.wood}
              />
              <mesh
                geometry={nodes['stick_pineapple_Material_#63_0'].geometry}
                material={materials.Material_63}
              />
              <mesh
                geometry={nodes['stick_pineapple_Material_#66_0'].geometry}
                material={materials.Material_66}
              />
              <mesh
                geometry={nodes['stick_pineapple_Material_#64_0'].geometry}
                material={materials.Material_64}
              />
            </group>
          </group>
          <group position={[34.511, -39.124, 16.553]} scale={2.54}>
            <mesh
              geometry={nodes.watermelon2_watermelon_0.geometry}
              material={materials.watermelon}
              position={[-7.115, -0.683, 2.025]}
            />
          </group>
          <group position={[-31.244, 34.179, 51.812]} scale={2.54}>
            <group position={[0, 0, -1.895]}>
              <mesh
                geometry={nodes.stick_strawberry_wood_0.geometry}
                material={materials.wood}
              />
              <mesh
                geometry={nodes['stick_strawberry_Material_#67_0'].geometry}
                material={materials.Material_67}
              />
              <mesh
                geometry={nodes['stick_strawberry_Material_#70_0'].geometry}
                material={materials.Material_70}
              />
              <mesh
                geometry={nodes['stick_strawberry_Material_#71_0'].geometry}
                material={materials.Material_71}
              />
            </group>
          </group>
          <group position={[38.104, 34.742, 56.138]} scale={2.54}>
            <group position={[0, 0, -1.895]}>
              <mesh
                geometry={nodes.stick_orange_wood_0.geometry}
                material={materials.wood}
              />
              <mesh
                geometry={nodes['stick_orange_Material_#58_0'].geometry}
                material={materials.Material_58}
              />
              <mesh
                geometry={nodes['stick_orange_Material_#61_0'].geometry}
                material={materials.Material_61}
              />
              <mesh
                geometry={nodes['stick_orange_Material_#60_0'].geometry}
                material={materials.Material_60}
              />
            </group>
          </group>
          <mesh
            geometry={nodes['sub_stall2_Material_#27_0'].geometry}
            material={materials.Material_27}
            position={[34.469, -38.837, 15.24]}
            scale={2.54}
          />
          <group position={[34.411, 45.359, 53.391]} scale={2.54}>
            <mesh
              geometry={nodes.orange_orange_0.geometry}
              material={materials.orange}
              position={[-8.289, 1.121, 0.418]}
            />
          </group>
          <group position={[34.288, 19.98, 47.195]} scale={2.54}>
            <mesh
              geometry={nodes.watermelon1_watermelon_0.geometry}
              material={materials.watermelon}
              position={[-3.253, -0.308, -0.669]}
            />
          </group>
          <group position={[57.161, -14.046, 33.979]} scale={2.54}>
            <group position={[0, 0, -1.895]}>
              <mesh
                geometry={nodes.stick_apple_wood_0.geometry}
                material={materials.wood}
              />
              <mesh
                geometry={nodes['stick_apple_Material_#40_0'].geometry}
                material={materials.Material_40}
              />
              <mesh
                geometry={nodes['stick_apple_Material_#42_0'].geometry}
                material={materials.Material_42}
              />
              <mesh
                geometry={nodes['stick_apple_Material_#41_0'].geometry}
                material={materials.Material_41}
              />
            </group>
          </group>
          <group position={[-34.621, 21.936, 45.447]} scale={2.54}>
            <group position={[3.191, -1.566, -3.06]}>
              <mesh
                geometry={nodes.pSphere219_lambert3_0.geometry}
                material={materials.lambert3}
              />
              <mesh
                geometry={nodes.pSphere219_lambert2_0.geometry}
                material={materials.lambert2}
              />
              <mesh
                geometry={nodes.pSphere219_lambert4_0.geometry}
                material={materials.lambert4}
              />
              <mesh
                geometry={nodes.pSphere219_lambert3_0_1.geometry}
                material={materials.lambert3_0}
              />
              <mesh
                geometry={nodes.pSphere219_lambert4_0_1.geometry}
                material={materials.lambert4_0}
              />
              <mesh
                geometry={nodes.pSphere219_lambert2_0_1.geometry}
                material={materials.lambert2_0}
              />
            </group>
          </group>
          <group position={[-34.155, -38.807, 25.06]} scale={2.54}>
            <group position={[-0.078, -6.002, 1.795]}>
              <mesh
                geometry={nodes.strawberry2_lambert3_0.geometry}
                material={materials.lambert3}
              />
              <mesh
                geometry={nodes.strawberry2_lambert3_0_1.geometry}
                material={materials.lambert3}
              />
              <mesh
                geometry={nodes.strawberry2_lambert2_0.geometry}
                material={materials.lambert2}
              />
              <mesh
                geometry={nodes.strawberry2_lambert4_0.geometry}
                material={materials.lambert4}
              />
            </group>
          </group>
          <group position={[34.75, -3.394, 35.838]} scale={2.54}>
            <group position={[-11.801, 2.766, -1.75]}>
              <mesh
                geometry={nodes.apple1_apple_0.geometry}
                material={materials.apple}
              />
              <mesh
                geometry={nodes.apple1_apple_0_1.geometry}
                material={materials.apple}
              />
              <mesh
                geometry={nodes.apple1_apple_0_2.geometry}
                material={materials.apple}
              />
              <mesh
                geometry={nodes.apple1_apple_0_3.geometry}
                material={materials.apple}
              />
            </group>
          </group>
          <mesh
            geometry={nodes['stall_Material_#27_0'].geometry}
            material={materials.Material_27}
            position={[0, 20.84, 27.959]}
            scale={2.54}
          />
          <group position={[-35.023, -3.578, 34.301]} scale={2.54}>
            <group position={[-2.097, 2.79, -1.141]}>
              <mesh
                geometry={nodes.apple2_apple_0.geometry}
                material={materials.apple}
              />
              <mesh
                geometry={nodes.apple2_apple_0_1.geometry}
                material={materials.apple}
              />
              <mesh
                geometry={nodes.apple2_apple_0_2.geometry}
                material={materials.apple}
              />
            </group>
          </group>
          <group position={[-32.95, 45.393, 46.623]} scale={2.54}>
            <group position={[-5.815, -1.846, -0.62]}>
              <mesh
                geometry={nodes.strawberry1_lambert3_0.geometry}
                material={materials.lambert3}
              />
              <mesh
                geometry={nodes.strawberry1_lambert3_0_1.geometry}
                material={materials.lambert3}
              />
              <mesh
                geometry={nodes.strawberry1_lambert2_0.geometry}
                material={materials.lambert2}
              />
              <mesh
                geometry={nodes.strawberry1_lambert4_0.geometry}
                material={materials.lambert4}
              />
            </group>
          </group>
          <mesh
            geometry={nodes['sub_stall1_Material_#27_0'].geometry}
            material={materials.Material_27}
            position={[-33.204, -38.837, 15.24]}
            scale={2.54}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/fruit_stall/Fruitstore.gltf');
