/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 mushroom.gltf 
Author: Ergoni (https://sketchfab.com/Ergoni)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mushroom-village-house-4597d460ff1d4ed795563293f83d39a8
Title: Mushroom Village - House
*/
import React from 'react';

import { useGLTF } from '@react-three/drei';

export function Mushroom(props) {
  const { nodes, materials } = useGLTF('/models/mushroom/mushroom.gltf');
  return (
    <group {...props} dispose={null}>
      <group scale={1}>
        <mesh
          geometry={nodes.House_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Mushroom_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          position={[-9.782, 0.708, -90.997]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Rocks_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          position={[-64.48, -0.405, 4.574]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Rocks001_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          position={[-58.349, 26.699, 6.814]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Rocks002_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          position={[-64.48, 0, 4.574]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Rocks003_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          position={[-67.868, 26.699, 14.579]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Base_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Rocks004_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          position={[-114.633, 1.464, -4.264]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Rocks005_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          position={[-125.299, 1.464, 17.146]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Rocks006_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          position={[-140.872, 1.464, -7.41]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Rocks007_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          position={[-126.672, 1.464, -22.096]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Grass_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          position={[-102.99, -0.854, 25.699]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Rocks008_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          position={[-143.732, 1.464, -34.3]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Mushroom001_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          position={[-48.406, 0.708, -86.579]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Mushroom002_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          position={[30.243, 0.708, 75.299]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Mushroom003_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          position={[2.343, 0.708, 109.983]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Mushroom004_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          position={[-28.482, 0.708, 96.281]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Leaf001_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          position={[-58.691, -1.139, -85.1]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Leaf002_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          position={[-39.296, -1.188, 99.257]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Leaf003_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          position={[-7.794, -0.171, 121.221]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Leaf004_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          position={[-24.683, -0.448, -101.979]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Leaf005_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          position={[9.415, -1.966, -98.912]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Fence001_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          position={[-102.165, 11.949, -44.52]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Fence_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          position={[-50.488, 11.949, 125.245]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Barriel_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          position={[46.194, -0.268, -41.973]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Leaf_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          position={[86.135, -1.386, 3.636]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Barriel001_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          position={[72.663, -0.268, -29.714]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Barriel002_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          position={[67.994, -0.268, -58.331]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Sign_Atlas_Mushroom_0.geometry}
          material={materials.Atlas_Mushroom}
          position={[-91.972, 0, 41.397]}
          rotation={[-Math.PI / 2, 0, 0.502]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/models/mushroom/mushroom.gltf');
