/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ninja.gltf 
Author: little.bucket (https://sketchfab.com/little.bucket)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/animal-ninja-60bf79c6ed5841bfa548ce7508c7ebd3
Title: Animal Ninja
*/
import React from 'react';

import { useGLTF } from '@react-three/drei';

export function Ninja(props) {
  const { nodes, materials } = useGLTF('/models/ninja/ninja.gltf');
  return (
    <group {...props} dispose={null}>
      <group scale={10}>
        <group rotation={[-Math.PI / 2, 0, 5.2]}>
          <mesh
            geometry={nodes.Object_2.geometry}
            material={materials.lambert2SG}
          />
          <mesh
            geometry={nodes.Object_3.geometry}
            material={materials.lambert3SG}
          />
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials.lambert4SG}
          />
          <mesh
            geometry={nodes.Object_5.geometry}
            material={materials.lambert5SG}
          />
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials.lambert6SG}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/ninja/ninja.gltf');
